export { HistoryPanel } from '../../components/HistoryPanel'
export { SessionHeader } from '../../components/SessionHeader'
export { TabBar } from '../../components/TabBar'
export { TaskInput, type StartedSessionSummary } from '../../components/TaskInput'
export { TerminalPanel } from '../../components/TerminalPanel'
export { removeProposal } from './domain/diffProposals'
export { isSessionStatus } from './domain/sessionStatus'
export { TabsProvider, useTabs, type Tab, type TabsState } from './state/tabs'
export type { ActiveSessionMeta } from './types'
