export { SessionHeader } from '../../components/SessionHeader'
export { TerminalPanel } from '../../components/TerminalPanel'
export { removeProposal } from './domain/diffProposals'
export { isSessionStatus } from './domain/sessionStatus'
export { TabsProvider, useTabs, type Tab, type TabsState } from './state/tabs'
export type { ActiveSessionMeta, StartedSessionSummary } from './types'
