import type { MarketplaceExtension } from '../../../../shared/types'

export const EXTENSION_CATALOG: MarketplaceExtension[] = [
  {
    id: 'openai-developer-docs',
    name: 'OpenAI Developer Docs',
    summary: 'Adds the official OpenAI documentation MCP server to coding agents.',
    description:
      'Use this when agents need current OpenAI API, Codex, ChatGPT Apps, and Agents SDK documentation.',
    publisher: 'OpenAI',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'docs', 'openai'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    recommended: true,
    homepageUrl: 'https://developers.openai.com',
    documentationUrl: 'https://developers.openai.com/codex',
    permissions: ['Network access to OpenAI developer documentation'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'openaiDeveloperDocs',
        transport: 'http',
        url: 'https://developers.openai.com/mcp',
      },
    ],
  },
  {
    id: 'context7-docs',
    name: 'Context7 Docs',
    summary: 'Adds Context7 as a documentation lookup MCP server.',
    description:
      'Use this for framework and library documentation lookups without copying docs into prompts.',
    publisher: 'Context7',
    category: 'mcp-server',
    source: 'community',
    tags: ['mcp', 'docs'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    homepageUrl: 'https://context7.com',
    permissions: ['Network access to Context7 documentation lookup'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'context7',
        transport: 'http',
        url: 'https://mcp.context7.com/mcp',
      },
    ],
  },
  {
    id: 'mcp-everything-test',
    name: 'MCP Everything Test Server',
    summary: 'Installs the official MCP test server through npx.',
    description:
      'Useful for validating MCP startup, tool discovery, and approval flows in local agent sessions.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'test', 'local'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl: 'https://github.com/modelcontextprotocol/servers',
    setupNotes: ['Requires Node.js and npx on PATH.'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'mcp_everything',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-everything'],
      },
    ],
  },
  {
    id: 'lobrecs-clean-code-skill',
    name: 'Lobrecs Clean Code Skill',
    summary: 'Installs a compact coding checklist for Codex and OpenCode.',
    description:
      'A repo-safe implementation checklist that reinforces typed contracts, main/preload/renderer boundaries, and focused tests.',
    publisher: 'Lobrecs',
    category: 'skill',
    source: 'curated',
    tags: ['skill', 'quality'],
    targetAgents: ['codex', 'opencode'],
    featured: true,
    recommended: true,
    setupNotes: ['Project scope writes .codex/skills and .opencode/instructions files.'],
    artifacts: [
      {
        kind: 'skill',
        skillName: 'lobrecs-clean-code',
        description: 'Apply Lobrecs Agent clean-code rules during implementation work.',
        body: [
          '---',
          'name: lobrecs-clean-code',
          'description: Apply Lobrecs Agent clean-code rules during implementation work.',
          '---',
          '',
          '# Lobrecs Clean Code',
          '',
          '- Keep privileged filesystem, process, and SQLite work in the main process.',
          '- Expose renderer access only through narrow preload APIs.',
          '- Add shared contracts before new cross-process behavior.',
          '- Do not persist API keys or provider secrets.',
          '- Keep domain rules testable without Electron, React, SQLite, or shell commands.',
          '- Add focused tests beside changed source files.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'opencode-helicone-plugin',
    name: 'OpenCode Helicone Plugin',
    summary: 'Adds the Helicone session plugin package to OpenCode.',
    description:
      'Installs the OpenCode plugin package reference. Provider credentials remain external environment configuration.',
    publisher: 'OpenCode',
    category: 'plugin',
    source: 'community',
    tags: ['plugin', 'observability'],
    targetAgents: ['opencode'],
    setupNotes: ['Configure Helicone credentials outside Lobrecs Agent before running OpenCode.'],
    artifacts: [
      {
        kind: 'plugin',
        agentId: 'opencode',
        packageName: 'opencode-helicone-session',
      },
    ],
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP',
    summary: 'Adds browser automation tools for local web verification.',
    description:
      'Useful when coding agents need to open pages, inspect accessibility snapshots, and validate frontend behavior through Playwright.',
    publisher: 'Microsoft Playwright',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'browser', 'testing', 'playwright'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    recommended: true,
    homepageUrl: 'https://playwright.dev',
    documentationUrl: 'https://www.npmjs.com/package/@playwright/mcp',
    setupNotes: ['Requires Node.js 18+ and downloads browser support on first use when needed.'],
    permissions: ['Can automate browsers and inspect pages requested by the agent'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'playwright',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@playwright/mcp@latest'],
      },
    ],
  },
  {
    id: 'filesystem-mcp',
    name: 'Filesystem MCP',
    summary: 'Adds a local filesystem MCP server for controlled file access experiments.',
    description:
      'Best for testing MCP roots, file browsing, and read/write tool approval flows without wiring a custom server.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'filesystem', 'local'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    requiresProject: true,
    setupNotes: [
      'Project scope limits the server argument to the selected repository path.',
      'Review tool approvals carefully because this server can read and write files within its root.',
    ],
    permissions: ['Reads and writes files under the configured project root'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'filesystem',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '${projectPath}'],
      },
    ],
  },
  {
    id: 'sequential-thinking-mcp',
    name: 'Sequential Thinking MCP',
    summary: 'Adds a structured planning tool for complex agent reasoning.',
    description:
      'Gives agents a dedicated MCP tool for stepwise planning, revision, and branching before they edit code.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'planning', 'reasoning'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl:
      'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
    setupNotes: ['Requires Node.js and npx on PATH.'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'sequential_thinking',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
      },
    ],
  },
  {
    id: 'memory-mcp',
    name: 'Memory MCP',
    summary: 'Adds a local knowledge graph MCP server for durable agent facts.',
    description:
      'Useful for experiments where agents need a small graph of entities, observations, and relationships outside the prompt.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'memory', 'knowledge'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
    setupNotes: ['Keep sensitive personal data out of memory server entries.'],
    permissions: ['Persists user-approved knowledge graph data locally'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'memory',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-memory'],
      },
    ],
  },
  {
    id: 'clean-review-skill',
    name: 'Lobrecs Clean Review Skill',
    summary: 'Installs the review checklist used for bug-first code reviews.',
    description:
      'Guides review agents to focus on correctness, regressions, security, and missing verification before style notes.',
    publisher: 'Lobrecs',
    category: 'skill',
    source: 'curated',
    tags: ['skill', 'review', 'quality'],
    targetAgents: ['codex', 'opencode'],
    recommended: true,
    setupNotes: ['Project scope writes .codex/skills and .opencode/instructions files.'],
    artifacts: [
      {
        kind: 'skill',
        skillName: 'lobrecs-clean-review',
        description: 'Review code using Lobrecs Agent bug-first review rules.',
        body: [
          '---',
          'name: lobrecs-clean-review',
          'description: Review code using Lobrecs Agent bug-first review rules.',
          '---',
          '',
          '# Lobrecs Clean Review',
          '',
          '- Lead with bugs, regressions, security issues, and missing verification.',
          '- Ground findings in file and line references.',
          '- Avoid style-only findings unless they hide a real maintainability risk.',
          '- Call out Electron boundary violations and secret persistence immediately.',
          '- Mention residual test gaps even when no blocking findings are found.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'mcp-registry-provider',
    name: 'MCP Registry Provider',
    summary: 'Tracks the official MCP registry as a future online catalog source.',
    description:
      'A provider entry for discovering MCP packages from registry metadata once online provider sync is enabled.',
    publisher: 'Model Context Protocol',
    category: 'provider',
    source: 'official',
    tags: ['provider', 'registry', 'mcp'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    homepageUrl: 'https://modelcontextprotocol.io',
    documentationUrl: 'https://modelcontextprotocol.io/registry/package-types',
    setupNotes: ['Provider sync is read-only in this release; direct installs use curated entries.'],
    artifacts: [],
  },
  {
    id: 'openai-plugins-provider',
    name: 'OpenAI Plugins Provider',
    summary: 'Groups OpenAI-built Codex capabilities and skills surfaced by Lobrecs Agent.',
    description:
      'Use this provider lane to keep OpenAI-developed tools separate from community marketplace entries.',
    publisher: 'OpenAI',
    category: 'provider',
    source: 'official',
    tags: ['provider', 'plugins', 'skills', 'openai'],
    targetAgents: ['codex'],
    homepageUrl: 'https://developers.openai.com/codex',
    setupNotes: ['Provider sync can later hydrate this lane from an API without changing the renderer.'],
    artifacts: [],
  },
]
