import type { MarketplaceExtension } from '../../../../shared/types'

type SkillsShCatalogInput = {
  id: string
  name: string
  summary: string
  description: string
  publisher: string
  packageName: string
  skillName: string
  cliSkillName?: string
  tags: string[]
  homepageUrl: string
  featured?: boolean
  recommended?: boolean
}

const SKILLS_SH_TARGET_AGENTS = ['claude-code', 'codex', 'opencode'] as const

function skillsShSkill(input: SkillsShCatalogInput): MarketplaceExtension {
  const extension: MarketplaceExtension = {
    id: input.id,
    name: input.name,
    summary: input.summary,
    description: input.description,
    publisher: input.publisher,
    category: 'skill',
    source: 'external',
    tags: ['skill', 'skills.sh', ...input.tags],
    targetAgents: [...SKILLS_SH_TARGET_AGENTS],
    homepageUrl: input.homepageUrl,
    documentationUrl: 'https://www.skills.sh/docs/cli',
    setupNotes: [
      'Runs the official skills.sh CLI with npx from the main process.',
      'Project scope runs in the selected repository; global scope adds --global.',
      'Lobrecs Agent sets DISABLE_TELEMETRY=1 for the install command.',
    ],
    permissions: ['Downloads skill files from the configured skills.sh source'],
      artifacts: [
        {
          kind: 'skill',
          skillName: input.skillName,
          cliSkillName: input.cliSkillName ?? input.skillName,
          packageName: input.packageName,
          installUrl: input.homepageUrl,
          description: input.summary,
        },
    ],
  }
  if (input.featured !== undefined) extension.featured = input.featured
  if (input.recommended !== undefined) extension.recommended = input.recommended
  return extension
}

export const EXTENSION_CATALOG: MarketplaceExtension[] = [
  {
    id: 'openai-developer-docs',
    name: 'OpenAI Developer Docs',
    summary: 'Adds the official OpenAI documentation MCP server to coding agents.',
    description:
      'Use this when agents need current OpenAI API, Codex, ChatGPT Apps, and Agents SDK documentation.',
    publisher: 'OpenAI',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'docs', 'openai'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    recommended: true,
    homepageUrl: 'https://developers.openai.com',
    documentationUrl: 'https://developers.openai.com/codex',
    permissions: ['Network access to OpenAI developer documentation'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'openaiDeveloperDocs',
        transport: 'http',
        url: 'https://developers.openai.com/mcp',
      },
    ],
  },
  {
    id: 'context7-docs',
    name: 'Context7 Docs',
    summary: 'Adds Context7 as a documentation lookup MCP server.',
    description:
      'Use this for framework and library documentation lookups without copying docs into prompts.',
    publisher: 'Context7',
    category: 'mcp-server',
    source: 'community',
    tags: ['mcp', 'docs'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    homepageUrl: 'https://context7.com',
    permissions: ['Network access to Context7 documentation lookup'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'context7',
        transport: 'http',
        url: 'https://mcp.context7.com/mcp',
      },
    ],
  },
  {
    id: 'mcp-everything-test',
    name: 'MCP Everything Test Server',
    summary: 'Installs the official MCP test server through npx.',
    description:
      'Useful for validating MCP startup, tool discovery, and approval flows in local agent sessions.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'test', 'local'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl: 'https://github.com/modelcontextprotocol/servers',
    setupNotes: ['Requires Node.js and npx on PATH.'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'mcp_everything',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-everything'],
      },
    ],
  },
  {
    id: 'lobrecs-clean-code-skill',
    name: 'Lobrecs Clean Code Skill',
    summary: 'Installs a compact coding checklist for Codex and OpenCode.',
    description:
      'A repo-safe implementation checklist that reinforces typed contracts, main/preload/renderer boundaries, and focused tests.',
    publisher: 'Lobrecs',
    category: 'skill',
    source: 'curated',
    tags: ['skill', 'quality'],
    targetAgents: ['codex', 'opencode'],
    featured: true,
    recommended: true,
    setupNotes: ['Project scope writes .codex/skills and .opencode/instructions files.'],
    artifacts: [
      {
        kind: 'skill',
        skillName: 'lobrecs-clean-code',
        description: 'Apply Lobrecs Agent clean-code rules during implementation work.',
        body: [
          '---',
          'name: lobrecs-clean-code',
          'description: Apply Lobrecs Agent clean-code rules during implementation work.',
          '---',
          '',
          '# Lobrecs Clean Code',
          '',
          '- Keep privileged filesystem, process, and SQLite work in the main process.',
          '- Expose renderer access only through narrow preload APIs.',
          '- Add shared contracts before new cross-process behavior.',
          '- Do not persist API keys or provider secrets.',
          '- Keep domain rules testable without Electron, React, SQLite, or shell commands.',
          '- Add focused tests beside changed source files.',
        ].join('\n'),
      },
    ],
  },
  {
    id: 'opencode-helicone-plugin',
    name: 'OpenCode Helicone Plugin',
    summary: 'Adds the Helicone session plugin package to OpenCode.',
    description:
      'Installs the OpenCode plugin package reference. Provider credentials remain external environment configuration.',
    publisher: 'OpenCode',
    category: 'plugin',
    source: 'community',
    tags: ['plugin', 'observability'],
    targetAgents: ['opencode'],
    setupNotes: ['Configure Helicone credentials outside Lobrecs Agent before running OpenCode.'],
    artifacts: [
      {
        kind: 'plugin',
        agentId: 'opencode',
        packageName: 'opencode-helicone-session',
      },
    ],
  },
  {
    id: 'local-jsonrpc-workflow-hooks',
    name: 'Local JSON-RPC Workflow Hooks',
    summary: 'Registers a project-owned JSON-RPC hook process for workflow phases.',
    description:
      'Use this when a repository wants to decorate prompts, register review providers, observe quality gates, or gate retries through an explicitly trusted local subprocess.',
    publisher: 'Lobrecs',
    category: 'plugin',
    source: 'curated',
    tags: ['hooks', 'workflow', 'json-rpc'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    requiresProject: true,
    setupNotes: [
      'Create .lobrecs/extensions/hooks/index.mjs in the selected project before enabling.',
      'Hooks are installed disabled and untrusted; enable them only after reviewing the command.',
      'The hook process receives JSON-RPC on stdin and must write one JSON-RPC response to stdout.',
    ],
    permissions: [
      'Can decorate prompts before agent dispatch',
      'Can register review providers',
      'Can observe quality gate results',
      'Can allow or block retry attempts',
    ],
    executable: {
      command: '.lobrecs/extensions/hooks/index.mjs',
      runtime: 'node',
      hooks: [
        'prompt-decoration',
        'review-provider-registration',
        'quality-gate-observation',
        'retry-gating',
      ],
      capabilities: [
        'prompt:decorate',
        'review-provider:register',
        'quality-gate:observe',
        'retry:gate',
      ],
      scope: 'project',
      timeoutMs: 10_000,
    },
    artifacts: [],
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP',
    summary: 'Adds browser automation tools for local web verification.',
    description:
      'Useful when coding agents need to open pages, inspect accessibility snapshots, and validate frontend behavior through Playwright.',
    publisher: 'Microsoft Playwright',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'browser', 'testing', 'playwright'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    recommended: true,
    homepageUrl: 'https://playwright.dev',
    documentationUrl: 'https://www.npmjs.com/package/@playwright/mcp',
    setupNotes: ['Requires Node.js 18+ and downloads browser support on first use when needed.'],
    permissions: ['Can automate browsers and inspect pages requested by the agent'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'playwright',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@playwright/mcp@latest'],
      },
    ],
  },
  {
    id: 'filesystem-mcp',
    name: 'Filesystem MCP',
    summary: 'Adds a local filesystem MCP server for controlled file access experiments.',
    description:
      'Best for testing MCP roots, file browsing, and read/write tool approval flows without wiring a custom server.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'filesystem', 'local'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
    requiresProject: true,
    setupNotes: [
      'Project scope limits the server argument to the selected repository path.',
      'Review tool approvals carefully because this server can read and write files within its root.',
    ],
    permissions: ['Reads and writes files under the configured project root'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'filesystem',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '${projectPath}'],
      },
    ],
  },
  {
    id: 'sequential-thinking-mcp',
    name: 'Sequential Thinking MCP',
    summary: 'Adds a structured planning tool for complex agent reasoning.',
    description:
      'Gives agents a dedicated MCP tool for stepwise planning, revision, and branching before they edit code.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'planning', 'reasoning'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl:
      'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
    setupNotes: ['Requires Node.js and npx on PATH.'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'sequential_thinking',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
      },
    ],
  },
  {
    id: 'memory-mcp',
    name: 'Memory MCP',
    summary: 'Adds a local knowledge graph MCP server for durable agent facts.',
    description:
      'Useful for experiments where agents need a small graph of entities, observations, and relationships outside the prompt.',
    publisher: 'Model Context Protocol',
    category: 'mcp-server',
    source: 'official',
    tags: ['mcp', 'memory', 'knowledge'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    documentationUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
    setupNotes: ['Keep sensitive personal data out of memory server entries.'],
    permissions: ['Persists user-approved knowledge graph data locally'],
    artifacts: [
      {
        kind: 'mcp-server',
        serverName: 'memory',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-memory'],
      },
    ],
  },
  {
    id: 'clean-review-skill',
    name: 'Lobrecs Clean Review Skill',
    summary: 'Installs the review checklist used for bug-first code reviews.',
    description:
      'Guides review agents to focus on correctness, regressions, security, and missing verification before style notes.',
    publisher: 'Lobrecs',
    category: 'skill',
    source: 'curated',
    tags: ['skill', 'review', 'quality'],
    targetAgents: ['codex', 'opencode'],
    recommended: true,
    setupNotes: ['Project scope writes .codex/skills and .opencode/instructions files.'],
    artifacts: [
      {
        kind: 'skill',
        skillName: 'lobrecs-clean-review',
        description: 'Review code using Lobrecs Agent bug-first review rules.',
        body: [
          '---',
          'name: lobrecs-clean-review',
          'description: Review code using Lobrecs Agent bug-first review rules.',
          '---',
          '',
          '# Lobrecs Clean Review',
          '',
          '- Lead with bugs, regressions, security issues, and missing verification.',
          '- Ground findings in file and line references.',
          '- Avoid style-only findings unless they hide a real maintainability risk.',
          '- Call out Electron boundary violations and secret persistence immediately.',
          '- Mention residual test gaps even when no blocking findings are found.',
        ].join('\n'),
      },
    ],
  },
  ...[
    skillsShSkill({
      id: 'skills-sh-find-skills',
      name: 'Find Skills',
      summary: 'Adds a workflow for discovering and vetting skills from the open skills ecosystem.',
      description:
        'Use this when an agent should search skills.sh, compare install counts, and recommend useful skills before starting specialized work.',
      publisher: 'Vercel Labs',
      packageName: 'https://github.com/vercel-labs/add-skill',
      skillName: 'find-skills',
      tags: ['discovery', 'workflow', 'marketplace'],
      homepageUrl: 'https://skills.sh/vercel-labs/add-skill/find-skills',
      featured: true,
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-frontend-design',
      name: 'Frontend Design',
      summary: 'Anthropic frontend implementation guidance for polished UI work.',
      description:
        'A popular skills.sh skill for agents working on layouts, interaction quality, and frontend implementation details.',
      publisher: 'Anthropic',
      packageName: 'anthropics/skills',
      skillName: 'frontend-design',
      tags: ['frontend', 'design', 'ui'],
      homepageUrl: 'https://skills.sh/anthropics/skills/frontend-design',
      featured: true,
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-skill-creator',
      name: 'Skill Creator',
      summary: 'Guides agents through authoring reusable Agent Skills.',
      description:
        'Useful when a repeated workflow should become a portable SKILL.md package with clear trigger rules and supporting references.',
      publisher: 'Anthropic',
      packageName: 'anthropics/skills',
      skillName: 'skill-creator',
      tags: ['skills', 'authoring', 'agents'],
      homepageUrl: 'https://skills.sh/anthropics/skills/skill-creator',
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-pdf',
      name: 'PDF',
      summary: 'Adds PDF reading and transformation workflows for document-heavy tasks.',
      description:
        'Use this when agents need structured guidance for handling PDFs, extracting information, or preparing document outputs.',
      publisher: 'Anthropic',
      packageName: 'anthropics/skills',
      skillName: 'pdf',
      tags: ['documents', 'pdf'],
      homepageUrl: 'https://skills.sh/anthropics/skills/pdf',
    }),
    skillsShSkill({
      id: 'skills-sh-pptx',
      name: 'PPTX',
      summary: 'Adds PowerPoint deck creation and editing guidance.',
      description:
        'A document skill for slide deck workflows, presentation structure, and PPTX-oriented agent tasks.',
      publisher: 'Anthropic',
      packageName: 'anthropics/skills',
      skillName: 'pptx',
      tags: ['documents', 'slides', 'presentations'],
      homepageUrl: 'https://skills.sh/anthropics/skills/pptx',
    }),
    skillsShSkill({
      id: 'skills-sh-docx',
      name: 'DOCX',
      summary: 'Adds Word document creation and editing workflows.',
      description:
        'Use this for document-generation agents that need Word-oriented structure and editing conventions.',
      publisher: 'Anthropic',
      packageName: 'anthropics/skills',
      skillName: 'docx',
      tags: ['documents', 'word'],
      homepageUrl: 'https://skills.sh/anthropics/skills/docx',
    }),
    skillsShSkill({
      id: 'skills-sh-react-best-practices',
      name: 'React Best Practices',
      summary: 'Vercel Engineering guidance for React and Next.js performance.',
      description:
        'Covers waterfalls, bundle size, server rendering, client data fetching, rerenders, and related React performance concerns.',
      publisher: 'Vercel Labs',
      packageName: 'vercel-labs/agent-skills',
      skillName: 'react-best-practices',
      tags: ['react', 'nextjs', 'performance'],
      homepageUrl: 'https://skills.sh/vercel-labs/agent-skills/react-best-practices',
      featured: true,
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-web-design-guidelines',
      name: 'Web Design Guidelines',
      summary: 'Audits frontend UI code against accessibility, UX, and performance rules.',
      description:
        'Useful for review agents checking forms, focus states, dark mode, navigation state, motion, images, and touch interactions.',
      publisher: 'Vercel Labs',
      packageName: 'vercel-labs/agent-skills',
      skillName: 'web-design-guidelines',
      tags: ['frontend', 'accessibility', 'review'],
      homepageUrl: 'https://skills.sh/vercel-labs/agent-skills/web-design-guidelines',
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-react-native-guidelines',
      name: 'React Native Guidelines',
      summary: 'React Native and Expo guidance for performance and platform-specific UI.',
      description:
        'Adds mobile-focused guidance for layout, keyboard behavior, animation, images, state management, and platform APIs.',
      publisher: 'Vercel Labs',
      packageName: 'vercel-labs/agent-skills',
      skillName: 'react-native-guidelines',
      tags: ['react-native', 'expo', 'mobile'],
      homepageUrl: 'https://skills.sh/vercel-labs/agent-skills/react-native-guidelines',
    }),
    skillsShSkill({
      id: 'skills-sh-composition-patterns',
      name: 'Composition Patterns',
      summary: 'React composition guidance for scalable component APIs.',
      description:
        'Helps agents refactor prop-heavy components into clearer composition patterns, compound components, and reusable APIs.',
      publisher: 'Vercel Labs',
      packageName: 'vercel-labs/agent-skills',
      skillName: 'composition-patterns',
      cliSkillName: 'vercel-composition-patterns',
      tags: ['react', 'architecture', 'components'],
      homepageUrl: 'https://skills.sh/vercel-labs/agent-skills/vercel-composition-patterns',
    }),
    skillsShSkill({
      id: 'skills-sh-supabase-postgres-best-practices',
      name: 'Supabase Postgres Best Practices',
      summary: 'Supabase and Postgres implementation guidance for database-backed apps.',
      description:
        'Useful for agents designing tables, policies, migrations, and data-access flows in Supabase/Postgres projects.',
      publisher: 'Supabase',
      packageName: 'supabase/agent-skills',
      skillName: 'supabase-postgres-best-practices',
      tags: ['database', 'postgres', 'supabase'],
      homepageUrl: 'https://skills.sh/supabase/agent-skills/supabase-postgres-best-practices',
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-shadcn',
      name: 'shadcn',
      summary: 'Guidance for building and extending shadcn/ui interfaces.',
      description:
        'Adds shadcn/ui conventions for component composition, styling, and UI implementation workflows.',
      publisher: 'shadcn',
      packageName: 'shadcn/ui',
      skillName: 'shadcn',
      tags: ['ui', 'components', 'tailwind'],
      homepageUrl: 'https://skills.sh/shadcn/ui/shadcn',
    }),
    skillsShSkill({
      id: 'skills-sh-tdd',
      name: 'TDD',
      summary: 'Matt Pocock testing workflow for test-first implementation.',
      description:
        'Use this when agents should pin behavior with tests first, implement narrowly, and iterate through focused verification.',
      publisher: 'Matt Pocock',
      packageName: 'mattpocock/skills',
      skillName: 'tdd',
      tags: ['testing', 'quality', 'workflow'],
      homepageUrl: 'https://skills.sh/mattpocock/skills/tdd',
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-improve-codebase-architecture',
      name: 'Improve Codebase Architecture',
      summary: 'Guidance for architecture cleanup and higher-signal refactors.',
      description:
        'A code-quality skill for agents planning architectural improvements without drifting into broad formatting churn.',
      publisher: 'Matt Pocock',
      packageName: 'mattpocock/skills',
      skillName: 'improve-codebase-architecture',
      tags: ['architecture', 'refactor', 'quality'],
      homepageUrl: 'https://skills.sh/mattpocock/skills/improve-codebase-architecture',
    }),
    skillsShSkill({
      id: 'skills-sh-to-prd',
      name: 'To PRD',
      summary: 'Turns rough product requests into structured product requirements.',
      description:
        'Useful for product agents that need to turn early ideas into scoped requirements before implementation starts.',
      publisher: 'Matt Pocock',
      packageName: 'mattpocock/skills',
      skillName: 'to-prd',
      tags: ['product', 'planning', 'requirements'],
      homepageUrl: 'https://skills.sh/mattpocock/skills/to-prd',
    }),
    skillsShSkill({
      id: 'skills-sh-to-issues',
      name: 'To Issues',
      summary: 'Breaks product or engineering plans into issue-ready work items.',
      description:
        'Use this when agents need to convert plans into actionable backlog tickets with concrete acceptance criteria.',
      publisher: 'Matt Pocock',
      packageName: 'mattpocock/skills',
      skillName: 'to-issues',
      tags: ['planning', 'issues', 'backlog'],
      homepageUrl: 'https://skills.sh/mattpocock/skills/to-issues',
    }),
    skillsShSkill({
      id: 'skills-sh-systematic-debugging',
      name: 'Systematic Debugging',
      summary: 'Superpowers debugging workflow for reproducing and isolating failures.',
      description:
        'A structured debugging skill for agents that should gather evidence, form hypotheses, and verify fixes before handoff.',
      publisher: 'Superpowers',
      packageName: 'obra/superpowers',
      skillName: 'systematic-debugging',
      tags: ['debugging', 'workflow', 'quality'],
      homepageUrl: 'https://skills.sh/obra/superpowers/systematic-debugging',
      recommended: true,
    }),
    skillsShSkill({
      id: 'skills-sh-executing-plans',
      name: 'Executing Plans',
      summary: 'Superpowers execution workflow for working through existing plans.',
      description:
        'Useful when an agent should follow an established checklist, keep status visible, and avoid skipping verification steps.',
      publisher: 'Superpowers',
      packageName: 'obra/superpowers',
      skillName: 'executing-plans',
      tags: ['planning', 'execution', 'workflow'],
      homepageUrl: 'https://skills.sh/obra/superpowers/executing-plans',
    }),
    skillsShSkill({
      id: 'skills-sh-writing-plans',
      name: 'Writing Plans',
      summary: 'Superpowers workflow for creating concrete implementation plans.',
      description:
        'Adds planning guidance for agents that need to decompose work before editing code or coordinating several tasks.',
      publisher: 'Superpowers',
      packageName: 'obra/superpowers',
      skillName: 'writing-plans',
      tags: ['planning', 'workflow'],
      homepageUrl: 'https://skills.sh/obra/superpowers/writing-plans',
    }),
  ],
  {
    id: 'skills-sh-provider',
    name: 'skills.sh Provider',
    summary: 'Tracks skills.sh as a future online source for searchable agent skills.',
    description:
      'Provider lane for the open Agent Skills ecosystem. Curated skills are installable now; live API search can be enabled later when an API key is configured.',
    publisher: 'Vercel',
    category: 'provider',
    source: 'external',
    tags: ['provider', 'skills', 'skills.sh'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    homepageUrl: 'https://skills.sh',
    documentationUrl: 'https://www.skills.sh/docs/api',
    setupNotes: ['The public skills.sh API requires an API key; this release ships curated entries.'],
    artifacts: [],
  },
  {
    id: 'mcp-registry-provider',
    name: 'MCP Registry Provider',
    summary: 'Tracks the official MCP registry as a future online catalog source.',
    description:
      'A provider entry for discovering MCP packages from registry metadata once online provider sync is enabled.',
    publisher: 'Model Context Protocol',
    category: 'provider',
    source: 'official',
    tags: ['provider', 'registry', 'mcp'],
    targetAgents: ['claude-code', 'codex', 'opencode'],
    featured: true,
    homepageUrl: 'https://modelcontextprotocol.io',
    documentationUrl: 'https://modelcontextprotocol.io/registry/package-types',
    setupNotes: ['Provider sync is read-only in this release; direct installs use curated entries.'],
    artifacts: [],
  },
  {
    id: 'openai-plugins-provider',
    name: 'OpenAI Plugins Provider',
    summary: 'Groups OpenAI-built Codex capabilities and skills surfaced by Lobrecs Agent.',
    description:
      'Use this provider lane to keep OpenAI-developed tools separate from community marketplace entries.',
    publisher: 'OpenAI',
    category: 'provider',
    source: 'official',
    tags: ['provider', 'plugins', 'skills', 'openai'],
    targetAgents: ['codex'],
    homepageUrl: 'https://developers.openai.com/codex',
    setupNotes: ['Provider sync can later hydrate this lane from an API without changing the renderer.'],
    artifacts: [],
  },
]
